In [4]:
import pandas as pd
from wptab import get_tab

In [6]:
## example wikipedia url with multiple tables
wiki_url = "https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains#Country_code_top-level_domains"

In [7]:
## Extract a table searchig for specific header values
hvals = {"Name[6]", "Entity", "Explanation", "Notes", "Registry[6]"}
target = get_tab(wiki_url, hvals, search="head")
pd.DataFrame(target[1:], columns=target[0]).head()

,Name[6],Entity,Explanation,Notes,Registry[6],IDN,DNSSEC,SLD,IPv6
0,.ac,Ascension Island (United Kingdom),,"Commonly used for academic websites, such as u...",Ascension Island Network Information Centre (r...,Yes,Yes,Yes,Yes
1,.ad,Andorra,,"Local trademark, trade name or citizenship req...",Nic.ad,,Yes,Yes,
2,.ae,United Arab Emirates,,,,,No,Yes,
3,.af,Afghanistan,,,,,Yes,Yes,
4,.ag,Antigua and Barbuda,,Also unofficially used by German businesses (w...,,,Yes,Yes,

In [8]:
## Extract a table searchig for specific row values (target id "t_id" is zero based!)
rvals = {".actor", "actors"}
target = get_tab(wiki_url1, rvals, search="row", t_id=4)
pd.DataFrame(target[1:], columns=target[0]).head()

,Name,Target market,Restrictions,Operator/Registry,IDN,DNSSEC
0,.academy,academic institutes,—,Donuts[donuts 1],Yes,Yes
1,.accountant,accountants and accounting firms,—,Global Registry Services Ltd[48],Unknown,Yes
2,.accountants,accountants and accounting firms,—,Donuts[donuts 2],Yes,Yes
3,.active,general,—,The Active Network,Unknown,Yes
4,.actor,actors,—,Rightside Group[n 1],Yes,Yes

In [9]:
## Extract a table searchig for specific column values (target id "t_id" is zero based!)
cvals = {"Bengali", "Bulgarian", "Chinese"}
target = get_tab(wiki_url1, cvals, search="column", t_id=3)
pd.DataFrame(target[1:], columns=target[0]).head(7)

,DNS name,IDN ccTLD,Country/Region,Language,Script,Transliteration,Comments,Other ccTLD,DNSSEC
0,xn--lgbbat1ad8j,.الجزائر,Algeria,Arabic,Arabic (Arabic),al-Jazā'ir,,.dz,No
1,xn--y9a3aq,.հայ,Armenia,Armenian,Armenian,hay,,.am,Yes
2,xn--mgbcpq6gpa1a,.البحرين,Bahrain,Arabic,Arabic,al-Bahrain,Not in use,.bh,No
3,xn--54b7fta0cc,.বাংলা,Bangladesh,Bengali,Bengali,Bangla,,.bd,Yes
4,xn--90ais,.бел,Belarus,Belarusian,Cyrillic,bel,,.by,No
5,xn--90ae,.бг[44],Bulgaria,Bulgarian,Cyrillic,bg,,.bg,No
6,xn--fiqs8s,.中国,China,Chinese,Chinese (Simplified),Zhōngguó,,.cn,Yes